# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Article.destroy_all

Article.create(
  publication_date: "2023-11-09",
  category: "Décryptage",
  title: "Pourquoi les collaborateurs partent ? Comment les inciter à rester ? Exploration au pays de la rétention.",
  paragraphes1: " <strong> Tout d'abord, posons nous sur les causes de départ des collaborateurs. Il existe plusieurs raisons qui expliquent un départ des collaborateurs, nous avons délibéremment choisi d'en analyser 4 : </strong> <br/> <br/>
  <strong> 1 - Le manque de perspectives d'évolution : </strong> d'après une enquête publiée par <a href='https://www.altays.com/fr/talent/la-montee-en-competences-levier-de-fidelisation-des-talents-en-entreprise-etude-menee-avec-opinionway-et-altays/'> OpinionWay </a> en octobre 2022, les répondants soulignent le manque de perspectives d’évolution de carrière comme la principale raison d'une démission. Lorsque les collaborateurs se sentent bloqués dans leur carrière et ne voient aucune possibilité de croissance, ils cherchent souvent de nouvelles opportunités ailleurs. <br/> <br/>
  <strong> 2 - Des relations managériales dégradées : </strong> 34% des salariés ne se sentent ni écoutés, ni compris par leur manager. C'est ce que révèle une <a href='https://www.cegos.fr/ressources/enquetes/climat-social-qvt-barometre-cegos'> enquête Cégos </a> publiée fin 2018 et relayée par le Figaro. Ce constat souligne l'importance d'une communication efficace et de relations managériales empathiques pour favoriser un environnement de travail positif. <br/> <br/>
  <strong> 3 - Le manque d'accompagnement des managers : </strong> 50% des salariés expriment un sentiment de négligence et un manque d’accompagnement de la part de leur manager, c'est ce que révèle le <a href='https://www.academieduservice.com/publication/barometre-symetrie-attentions-2023-satisfaction-collaborateurs/'> Baromètre National 2023 de la Symétrie des Attentions©. </a> À l'heure où la satisfaction globale des collaborateurs dans leur entreprise est en chute libre (-12 points en 1 an, passant à 54%), l'accompagnement managérial est un levier important pour fidéliser et redorer l'expérience collaborateur.  <br/> <br/>
  <strong> 4 - Le manque de reconnaissance et de valorisation : </strong> l'absence de reconnaissance pour le travail accompli est une cause fréquente de départ des employés. Lorsqu'ils ne se sentent pas appréciés ni valorisés, leur motivation et leur engagement peuvent diminuer, les poussant à rechercher un environnement où leur travail est reconnu. 50% des collaborateurs perçoivent un déficit de reconnaissance envers leurs efforts et leur travail au sein de l’entreprise d'après le <a href='https://www.academieduservice.com/publication/barometre-symetrie-attentions-2023-satisfaction-collaborateurs/'> Baromètre National 2023 de la Symétrie des Attentions© </a>.<br/> <br/>",

  paragraphes2: "<strong> Pour faire écho aux raisons de départ évoqués ci-dessus, nous avons identifié 4 leviers d'action qui nous semblent prioritaires dans le contexte actuel, voyons ça de plus près : </strong> <br/> <br/>
  <strong> 1 - Offrir des opportunités de développement professionnel : </strong> aujourd'hui plus qu'hier, les entreprises doivent investir dans le développement de leurs employés </strong> en leur proposant de construire des plans de carrière clairs, engageants et déclinés en actions concrètes. En offrant des perspectives d'évolution coconstruits avec le collaborateur et alignées avec le projet d'entreprise, le collaborateur entrevoit le chemin qu'il a à parcourir et sera ainsi plus enclin à rester et à s'investir dans l'entreprise. <br/> <br/>
  <strong> 2 - Renforcer la relation managériale : </strong>  à l'heure où les liens humains sont challengés par des changements de paradigmes profonds : nouveaux modes de travail hybrides, quête de sens, guerre des talents… la relation entre un collaborateur et son manager s'avère être un pilier important pour favoriser l'épanouissement des individus. Il est ainsi crucial d'accompagner les managers pour qu'ils soient de bons leaders, capables de communiquer efficacement, d'écouter les besoins des employés et de les soutenir dans leur développement. <br/> <br/>
  <strong> 3 - Structurer l'accompagnement de carrière : </strong>  au-delà d'établir une relation collaborateur / manager plus humaine et basée sur la confiance, il est nécessaire de structurer cette collaboration pour quelle soit une source de performance. Et un collaborateur performant est notamment un individu qui sait où il va, pourquoi et comment. Prenons le temps de répondre à ces questions : quelle histoire le binôme souhaite-t-il écrire dans l'entreprise ? Qu'est-il possible de faire dans le contexte de l'organisation ? Comment vont-ils pouvoir la réaliser ? <br/> <br/>
  <strong> 4 - Reconnaître et récompenser les performances : </strong> la reconnaissance régulière des réalisations et des contributions des employés est essentielle. Cela peut se faire par le biais de récompenses, de programmes de reconnaissance ou de simples mots de remerciement. La valorisation des accomplissements renforce le sentiment d'appartenance et la motivation des collaborateurs.<br/> <br/> ",

  paragraphes3: "<strong> Pour créer un environnement propice à la satisfaction professionnelle et donc la rétention des collaborateurs, Camino a choisi de s'investir sur 3 sujets complémentaires :</strong> <br/> <br/>
  <strong> 1 - Rendre les collaborateurs acteurs leur développement professionnel : </strong> afin de favoriser le développement professionnel des collaborateurs, il est essentiel de leur donner les moyens de devenir autonomes dans leur parcours. Cela peut être réalisé en leur fournissant les clés et la méthode nécessaires pour se questionner et se comprendre. Les employés doivent être encouragés à réfléchir à leurs aspirations, leurs forces et leurs moteurs, et à les aligner avec les objectifs de l'entreprise. En les aidant à répondre à la question fondamentale 'quelle histoire je souhaite écrire dans mon entreprise', les employés peuvent se fixer des objectifs clairs et se sentir investis dans un projet de carrière cohérent et motivant.<br/> <br/>
  <strong> 2 - Proposer un cadre pour renforcer les relations managériales : </strong> pour nouer de véritables liens de confiance, nous invitons les managers et les collaborateurs à mieux se comprendre et à coconstruire ensemble un projet de carrière cohérent, aligné avec les aspirations du collaborateur et le projet d'entreprise. Le manager, en s'impliquant dans le projet de carrière de ses équipes, favorise la création d'un environnement propice à l'épanouissement professionnel et à la rétention des collaborateurs.  <br/> <br/>
  <strong> 3 - Comprendre pour mieux retenir : </strong> en invitant les collaborateurs à exprimer leurs aspirations, leurs forces et leurs moteurs, l'entreprise dispose finalement d'informations précieuses pour prévenir les risques RH et affiner la stratégie. Camino aide les dirigeants, responsables RH et managers d'entreprises à répondre à cette question fondamentale : 'Qui sont mes collaborateurs et comment envisagent-ils leur futur dans notre organisation ?' Cette connaissance permet de répondre aux besoins des collaborateurs et ainsi libérer leur plein potentiel en les orientant efficacement dans l'entreprise. <br/> <br/>",
  title1: "4 raisons qui expliquent le départ des collaborateurs",
  title2: "4 pistes de réflexion pour retenir durablement ses collaborateurs",
  title3: "Et si on essayait la méthode Camino ?",
  url: "https://www.lefigaro.fr/sports/tennis/roland-garros/rafa-xiv-le-roi-soleil-la-presse-espagnole-comblee-par-le-14e-sacre-de-nadal-a-roland-garros-20220606",
  image: "imagearticle1.jpeg",
  reading_time: 7,
  imagesynthese: "synthesearticle1.png",
  # <img_tag src='<%= asset_path('imgsynthesearticle1.png') %>' sizes='(max-width: 767px) 16vw, 13vw' srcset='<%= asset_path('imgsynthesearticle1.png') %> 500w, <%= asset_path('imgsynthesearticle1.png') %> 660w' alt='picture representing 3 happy workers' id='defi-solution-icon'>",
  summary: "La compréhension des raisons qui poussent les collaborateurs à quitter leur entreprise est essentielle pour mettre en place des mesures visant à les retenir. Les entreprises disposent d'une panoplie de leviers activables pour améliorer leur capacité à retenir les talents et à favoriser leur performance à long terme. Partons à leur rencontre."
)

Article.create(
  publication_date: "2021-04-12",
  category: "Projection professionnelle",
  title: "Salut les zouaves",
  paragraphes1: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  paragraphes2: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  paragraphes3: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  title1: "Rafael Nadal remporte son 14ème titre à Roland-Garros",
  title2: "Rafael Nadal remporte son 14ème titre à Roland-Garros",
  title3: "Rafael Nadal remporte son 14ème titre à Roland-Garros",
  url: "https://www.lefigaro.fr/sports/tennis/roland-garros/rafa-xiv-le-roi-soleil-la-presse-espagnole-comblee-par-le-14e-sacre-de-nadal-a-roland-garros-20220606",
  image: "https://cdn-s-www.republicain-lorrain.fr/images/CA4317F0-F9EF-4335-A6CB-BC6E1A8F48B2/NW_raw/rafael-nadal-a-elimine-stefano-travaglia-photo-thomas-samson-afp-1601668500.jpg",
  reading_time: 5,
  summary: 'Ceci est un résumé de l\'article, dorem insitu blabla blabla blabla bla bla'
)

Article.create(
  publication_date: "2021-04-12",
  category: "Projection professionnelle",
  title: "Salut les zouaves",
  paragraphes1: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  paragraphes2: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  paragraphes3: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  title1: "Rafael Nadal remporte son 14ème titre à Roland-Garros",
  title2: "Rafael Nadal remporte son 14ème titre à Roland-Garros",
  title3: "Rafael Nadal remporte son 14ème titre à Roland-Garros",  url: "https://www.lefigaro.fr/sports/tennis/roland-garros/rafa-xiv-le-roi-soleil-la-presse-espagnole-comblee-par-le-14e-sacre-de-nadal-a-roland-garros-20220606",
  image: "https://cdn-s-www.republicain-lorrain.fr/images/CA4317F0-F9EF-4335-A6CB-BC6E1A8F48B2/NW_raw/rafael-nadal-a-elimine-stefano-travaglia-photo-thomas-samson-afp-1601668500.jpg",
  reading_time: 5,
  summary: 'Ceci est un résumé de l\'article, dorem insitu blabla blabla blabla bla bla'
)

Article.create(
  publication_date: "2021-04-12",
  category: "Projection professionnelle",
  title: "Salut les zouaves",
  paragraphes1: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  paragraphes2: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  paragraphes3: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  title1: "Rafael Nadal remporte son 14ème titre à Roland-Garros",
  title2: "Rafael Nadal remporte son 14ème titre à Roland-Garros",
  title3: "Rafael Nadal remporte son 14ème titre à Roland-Garros",  url: "https://www.lefigaro.fr/sports/tennis/roland-garros/rafa-xiv-le-roi-soleil-la-presse-espagnole-comblee-par-le-14e-sacre-de-nadal-a-roland-garros-20220606",
  image: "https://cdn-s-www.republicain-lorrain.fr/images/CA4317F0-F9EF-4335-A6CB-BC6E1A8F48B2/NW_raw/rafael-nadal-a-elimine-stefano-travaglia-photo-thomas-samson-afp-1601668500.jpg",
  reading_time: 5,
  summary: 'Ceci est un résumé de l\'article, dorem insitu blabla blabla blabla bla bla'

)

Article.create(
  publication_date: "2021-04-12",
  category: "Projection professionnelle",
  title: "Salut les zouaves",
  paragraphes1: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  paragraphes2: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  paragraphes3: "Rafael Nadal est une légende vivante du tennis et il l'a encore prouvé aujourd'hui en remportant son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Espagnol a écrasé son adversaire en finale, remportant le match en trois sets (6-1, 6-2, 6-0). Il s'agit de la quatrième fois que Nadal remporte le tournoi sans perdre un seul set, une performance exceptionnelle. Nadal est le roi de Roland-Garros, et il le prouve encore une fois cette année. Il a remporté son 14ème titre à Roland-Garros, un exploit incroyable ! L'Esp",
  title1: "Rafael Nadal remporte son 14ème titre à Roland-Garros",
  title2: "Rafael Nadal remporte son 14ème titre à Roland-Garros",
  title3: "Rafael Nadal remporte son 14ème titre à Roland-Garros",
  url: "https://www.lefigaro.fr/sports/tennis/roland-garros/rafa-xiv-le-roi-soleil-la-presse-espagnole-comblee-par-le-14e-sacre-de-nadal-a-roland-garros-20220606",
  image: "https://cdn-s-www.republicain-lorrain.fr/images/CA4317F0-F9EF-4335-A6CB-BC6E1A8F48B2/NW_raw/rafael-nadal-a-elimine-stefano-travaglia-photo-thomas-samson-afp-1601668500.jpg",
  reading_time: 5,
  summary: 'Ceci est un résumé de l\'article, dorem insitu blabla blabla blabla bla bla'
)
